POST http://localhost:8080/user
Content-Type: application/json

{}

###
GET http://localhost:8080/user

###
GET http://localhost:8080/user/list

###
GET http://localhost:8080/user/gender/1

###
GET http://localhost:8080/user/gender/all

###
GET http://localhost:8080/user/details

###
GET http://localhost:8080/user/where
