{{- if .Values.kafkaEnabled -}}

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-single
  labels:
    app: kafka-single
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      protocol: TCP
      nodePort: 30092
  selector:
    app: kafka-single

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-single
  labels:
    app: kafka-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-single
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-single
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: kafka-single
          imagePullPolicy: Never
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
              name: kafka-single
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-single:9092"
            - name: KAFKA_LISTENERS
              value: 'PLAINTEXT://:9092'
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: "test:1:1"

{{- end }}
