{{- if .Values.esEnabled -}}

---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
      name: rest
    - port: 9300
      targetPort: 9300
      name: inter-node

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  replicas: 1
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - name: "{{ .Chart.Name }}-persistent-storage"
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: cluster.name
              value: k8s-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "es-cluster-0.elasticsearch"
            - name: cluster.initial_master_nodes
              value: "es-cluster-0"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: "{{ .Chart.Name }}-persistent-storage"
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox:latest
          imagePullPolicy: Never
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      volumes:
        - name: "{{ .Chart.Name }}-persistent-storage"
          hostPath:
            path: "/mnt/k8s/infrastructure/{{ .Chart.Name }}/data"

{{- end }}
