{{- if .Values.redisEnabled -}}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30379
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: redis
          imagePullPolicy: Never
          image: redis:6-alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: "redis-persistent-storage"
              mountPath: /var/lib/redis
      volumes:
        - name: "redis-persistent-storage"
          hostPath:
            path: "/mnt/k8s/infrastructure/redis/data"

{{- end }}
