{{- if .Values.xxlJobEnabled -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30008
  selector:
    app: {{ .Chart.Name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: xuxueli/xxl-job-admin:2.2.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PARAMS
              value: "
              --spring.datasource.url=jdbc:mysql://{{ .Values.mysqlHost }}:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
              --spring.datasource.password={{ .Values.mysqlPassword }}
              "
          volumeMounts:
            - mountPath: /data/applogs
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir: {}

{{- end }}