{{- if .Values.zookeeperEnabled -}}

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-web-ui
  labels:
    app: zookeeper-web-ui
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31181
  selector:
    app: zookeeper-web-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-web-ui
  labels:
    app: zookeeper-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-web-ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper-web-ui
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zookeeper-web-ui
          imagePullPolicy: Never
          image: tobilg/zookeeper-webui
          ports:
            - containerPort: 8080
          env:
            - name: USER
              value: "admin"
            - name: PASSWORD
              value: "admin"

{{- end }}
