{{- if .Values.zookeeperEnabled -}}

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  type: NodePort
  ports:
    - name: client
      port: 2181
      protocol: TCP
      nodePort: 30181
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    app: zookeeper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zookeeper
          imagePullPolicy: Never
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
              name: zookeeper
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1

{{- end }}
