name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven package java
      run: mvn clean install --file java/pom.xml
    - name: Maven package springboot2
      run: mvn clean install --file springboot2/pom.xml