name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: prepare for deploy
      run: sed -i 's/my-secret-2/${{ secrets.OSS }}/g' settings.xml && sed -i 's/my-secret-1/${{ secrets.GPG }}/g' settings.xml
    - name: Build with Maven
      run: mvn -B clean install deploy --file pom.xml --settings settings.xml -Dgpg.passphrase=${{ secrets.GPG }}